# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2

workflows:
  version: 2
  jobs:
    test:
      docker:
        - image: cypress/base:14.16.0
      parallelism: 4
      steps:
        - run:
            command: |
              circleci tests glob "**/*.feature" | circleci tests split --split-by=timings