# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2

jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
    parallelism: 3
    steps:
      - run:
          command: |
            circleci tests glob "cypress/integration/features/UI/**/*.feature" | circleci tests split --split-by=timings